#!/bin/sh

if [ -r /etc/rc.conf ]; then
        . /etc/rc.conf
fi

start() {
    if [ -f /proc/gxp/dev_info/hw_features/dect ] && [ "`cat /proc/gxp/dev_info/hw_features/dect`" = "1" ]; then
            httpd -h /app/www -p ${web_port} &
    elif [ "`nvram get 190`" = "1" ]; then
       	    httpd -h /app/www -p ${web_port} &
	fi
}

stop() {
        killall -9 httpd
}

restart() {
        stop
        start
}

case "${1}" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
esac

exit $?
~                                                                                                                                          
~                                                                                                                                          
~            
