#!/bin/sh

start() {
# Patch WAN Mode switching cause LAN fail to access network.
#iptables -F

/etc/rc.d/init.d/wan_disconnect
ifconfig eth0 up
ifconfig eth0 0.0.0.0

pppoeclient&

sleep 1
i=1
#Exit if cable is detached.
if [ -f /sys/class/net/eth0/operstate -a "$(cat /sys/class/net/eth0/operstate)" = "down" ]; then
	exit 1
fi	
while [ $i -le 120 ]
do
   if [ -n "`ifconfig ppp0 2> /dev/null | grep RUNNING`" ]; then
   		exit 1
   fi
   sleep 1
   i=$(($i+1))
done
}

#let stop safe
stop() {
	ifconfig ppp0 down 2>/dev/null
	killall pppoecd 2> /dev/null
	killall pppoecd 2> /dev/null
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo $"Usage $0 {start|stop|restart}"
		exit 1
esac

exit $?
